# Generated by Django 5.1.7 on 2025-04-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpatient',
            old_name='name',
            new_name='first_name',
        ),
    ]
